from pathlib import Path
import numpy as np
import pandas as pd
ROOT=Path('.');POOL=ROOT/'data/processed/v59_expanded_bge_pairs.parquet';SAMPLE=ROOT/'data/raw/sample_submission.csv';ANCHOR=ROOT/'submissions/FINAL_MAIN_v22_vote_full_risky_big_v2.csv';TERMS=ROOT/'data/raw/terms.csv';ITEMS=ROOT/'data/raw/items.csv';SUB=ROOT/'submissions/final_candidates_v60';REV=ROOT/'reports/manual_review/review_v60_public080_bge_swaps.csv';SUM=ROOT/'reports/manual_review/v60_public080_bge_summary.csv'
def main():
 SUB.mkdir(parents=True,exist_ok=True);REV.parent.mkdir(parents=True,exist_ok=True);p=pd.read_parquet(POOL);sample=pd.read_csv(SAMPLE,usecols=['id']);sample.id=sample.id.astype(str);a=pd.read_csv(ANCHOR);a.id=a.id.astype(str);pred0=a.prediction.astype(np.int8).to_numpy();mp=pd.Series(pred0,index=a.id);valid=p.id_add.map(mp).eq(0)&p.id_drop.map(mp).eq(1)
 rt=p.root_add.eq(p.root_top1)|p.root_add.eq(p.root_top2);rs=p.same_root|((p.root_prob_add>=p.root_prob_drop+.04)&(p.root_prob_add>=.08)&rt);lex=(p.diff_v38_lex_score>0)&(p.diff_v33_ft_score>0)&(p.diff_v38_word_overlap_full>=0)&(p.diff_v38_must_token_coverage_full>=0)&(p.diff_v38_must_missing_ratio<=0)&(p.diff_v38_special_token_coverage_full>=0)&(p.diff_v43_query_pop_support>=0)&(p.robust_gain>=.12);title=(p.v38_title_missing_ratio_add<=.5)&(p.v38_word_overlap_title_add>=p.v38_word_overlap_title_drop)&(p.query_token_count>=2);ent=(p.diff_v38_number_match>=0)&(p.diff_v38_model_match>=0)&(p.diff_v38_brand_match>=0);base=valid&rs&lex&title&ent;idx=pd.Series(np.arange(len(sample)),index=sample.id);rows=[];reviews=[]
 modes={'ultra':base&(p.v55_prob>=.95)&(p.bge_add>=2.5)&(p.bge_gain>=2.5),'strict':base&(p.v55_prob>=.93)&(p.bge_add>=1.5)&(p.bge_gain>=2),'safe':base&(p.v55_prob>=.90)&(p.bge_add>=.5)&(p.bge_gain>=1.5)}
 for mode,mask in modes.items():
  sw=p[mask].sort_values(['bge_add','bge_gain','v55_prob'],ascending=False).drop_duplicates(['id_add','id_drop']).drop_duplicates('term_id');print(mode,len(sw));z=sw.head(350).copy();z['mode']=mode;reviews.append(z)
  for cap in [100,250,500,1000]:
   take=sw.head(cap);pred=pred0.copy();pred[idx.loc[take.id_add].to_numpy()]=1;pred[idx.loc[take.id_drop].to_numpy()]=0;name=f'v60_public080_{mode}_cap{cap}';out=SUB/(name+'.csv');pd.DataFrame({'id':sample.id,'prediction':pred}).to_csv(out,index=False);rows.append({'variant':name,'mode':mode,'accepted_pool':len(sw),'used_swaps':len(take),'bge_add_mean':float(take.bge_add.mean()),'bge_gain_mean':float(take.bge_gain.mean()),'v55_prob_mean':float(take.v55_prob.mean()),'diff_vs_public080':int((pred!=pred0).sum()),'ones':int(pred.sum()),'pos_ratio':float(pred.mean()),'file':str(out)})
 terms=pd.read_csv(TERMS,usecols=['term_id','query']);terms.term_id=terms.term_id.astype(str);items=pd.read_csv(ITEMS,usecols=['item_id','title','category']);items.item_id=items.item_id.astype(str);r=pd.concat(reviews,ignore_index=True).drop_duplicates(['id_add','id_drop']).merge(terms,on='term_id',how='left')
 for side in ['add','drop']:r=r.merge(items.drop_duplicates('item_id').rename(columns={'item_id':'item_id_'+side,'title':'title_'+side,'category':'category_'+side}),on='item_id_'+side,how='left')
 front=['mode','query_x','id_add','title_add','category_add','bge_add','id_drop','title_drop','category_drop','bge_drop','bge_gain','v55_prob'];r[[c for c in front if c in r]+[c for c in r if c not in front]].to_csv(REV,index=False);pd.DataFrame(rows).to_csv(SUM,index=False);print(pd.DataFrame(rows).to_string(index=False));print('outputs',REV,SUM)
if __name__=='__main__':main()
